package github.killarexe.copper_extension;

import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import oshi.util.tuples.Pair;

import java.util.HashMap;

public class CEMaps {
    public static final HashMap<Item, Pair<Item, Float>> OXIDATION_MAP_ITEMS = new HashMap<>();
    public static final HashMap<Item, Item> WAXING_MAP_ITEMS = new HashMap<>();
    public static final HashMap<Item, MobEffectInstance> ARMOR_EFFECTS = new HashMap<>();

    static {
        OXIDATION_MAP_ITEMS.put(Items.COPPER_BLOCK, new Pair<>(Items.EXPOSED_COPPER, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.EXPOSED_COPPER, new Pair<>(Items.WEATHERED_COPPER, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.WEATHERED_COPPER, new Pair<>(Items.OXIDIZED_COPPER, 1.0f));

        OXIDATION_MAP_ITEMS.put(Items.CUT_COPPER, new Pair<>(Items.EXPOSED_CUT_COPPER, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.EXPOSED_CUT_COPPER, new Pair<>(Items.WEATHERED_CUT_COPPER, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.WEATHERED_CUT_COPPER, new Pair<>(Items.OXIDIZED_CUT_COPPER, 1.0f));

        OXIDATION_MAP_ITEMS.put(Items.CUT_COPPER_SLAB, new Pair<>(Items.EXPOSED_CUT_COPPER_SLAB, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.EXPOSED_CUT_COPPER_SLAB, new Pair<>(Items.WEATHERED_CUT_COPPER_SLAB, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.WEATHERED_CUT_COPPER_SLAB, new Pair<>(Items.OXIDIZED_CUT_COPPER_SLAB, 1.0f));

        OXIDATION_MAP_ITEMS.put(Items.CUT_COPPER_STAIRS, new Pair<>(Items.EXPOSED_CUT_COPPER_STAIRS, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.EXPOSED_CUT_COPPER_STAIRS, new Pair<>(Items.WEATHERED_CUT_COPPER_STAIRS, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.WEATHERED_CUT_COPPER_STAIRS, new Pair<>(Items.OXIDIZED_CUT_COPPER_STAIRS, 1.0f));

        OXIDATION_MAP_ITEMS.put(Items.COPPER_BULB, new Pair<>(Items.EXPOSED_COPPER_BULB, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.EXPOSED_COPPER_BULB, new Pair<>(Items.WEATHERED_COPPER_BULB, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.WEATHERED_COPPER_BULB, new Pair<>(Items.OXIDIZED_COPPER_BULB, 1.0f));

        OXIDATION_MAP_ITEMS.put(Items.COPPER_DOOR, new Pair<>(Items.EXPOSED_COPPER_DOOR, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.EXPOSED_COPPER_DOOR, new Pair<>(Items.WEATHERED_COPPER_DOOR, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.WEATHERED_COPPER_DOOR, new Pair<>(Items.OXIDIZED_COPPER_DOOR, 1.0f));

        OXIDATION_MAP_ITEMS.put(Items.COPPER_GRATE, new Pair<>(Items.EXPOSED_COPPER_GRATE, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.EXPOSED_COPPER_GRATE, new Pair<>(Items.WEATHERED_COPPER_GRATE, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.WEATHERED_COPPER_GRATE, new Pair<>(Items.OXIDIZED_COPPER_GRATE, 1.0f));

        OXIDATION_MAP_ITEMS.put(Items.COPPER_TRAPDOOR, new Pair<>(Items.EXPOSED_COPPER_TRAPDOOR, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.EXPOSED_COPPER_TRAPDOOR, new Pair<>(Items.WEATHERED_COPPER_TRAPDOOR, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.WEATHERED_COPPER_TRAPDOOR, new Pair<>(Items.OXIDIZED_COPPER_TRAPDOOR, 1.0f));

        OXIDATION_MAP_ITEMS.put(Items.CHISELED_COPPER, new Pair<>(Items.EXPOSED_CHISELED_COPPER, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.EXPOSED_CHISELED_COPPER, new Pair<>(Items.WEATHERED_CHISELED_COPPER, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.WEATHERED_CHISELED_COPPER, new Pair<>(Items.OXIDIZED_CHISELED_COPPER, 1.0f));

        OXIDATION_MAP_ITEMS.put(Items.COPPER_LANTERN.unaffected(), new Pair<>(Items.COPPER_LANTERN.exposed(), 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.COPPER_LANTERN.exposed(), new Pair<>(Items.COPPER_LANTERN.weathered(), 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.COPPER_LANTERN.weathered(), new Pair<>(Items.COPPER_LANTERN.oxidized(), 1.0f));

        OXIDATION_MAP_ITEMS.put(Items.COPPER_CHEST, new Pair<>(Items.EXPOSED_COPPER_CHEST, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.EXPOSED_COPPER_CHEST, new Pair<>(Items.WEATHERED_COPPER_CHEST, 1.0f));
        OXIDATION_MAP_ITEMS.put(Items.WEATHERED_COPPER_CHEST, new Pair<>(Items.OXIDIZED_COPPER_CHEST, 1.0f));


        WAXING_MAP_ITEMS.put(Items.COPPER_BLOCK, Items.WAXED_COPPER_BLOCK);
        WAXING_MAP_ITEMS.put(Items.EXPOSED_COPPER, Items.WAXED_EXPOSED_COPPER);
        WAXING_MAP_ITEMS.put(Items.WEATHERED_COPPER, Items.WAXED_WEATHERED_COPPER);
        WAXING_MAP_ITEMS.put(Items.OXIDIZED_COPPER, Items.WAXED_WEATHERED_COPPER);

        WAXING_MAP_ITEMS.put(Items.CUT_COPPER, Items.WAXED_CUT_COPPER);
        WAXING_MAP_ITEMS.put(Items.EXPOSED_CUT_COPPER, Items.WAXED_EXPOSED_CUT_COPPER);
        WAXING_MAP_ITEMS.put(Items.WEATHERED_CUT_COPPER, Items.WAXED_WEATHERED_CUT_COPPER);
        WAXING_MAP_ITEMS.put(Items.OXIDIZED_CUT_COPPER, Items.WAXED_OXIDIZED_CUT_COPPER);

        WAXING_MAP_ITEMS.put(Items.CUT_COPPER_SLAB, Items.WAXED_CUT_COPPER_SLAB);
        WAXING_MAP_ITEMS.put(Items.EXPOSED_CUT_COPPER_SLAB, Items.WAXED_EXPOSED_CUT_COPPER_SLAB);
        WAXING_MAP_ITEMS.put(Items.WEATHERED_CUT_COPPER_SLAB, Items.WAXED_WEATHERED_CUT_COPPER_SLAB);
        WAXING_MAP_ITEMS.put(Items.OXIDIZED_CUT_COPPER_SLAB, Items.WAXED_OXIDIZED_CUT_COPPER_SLAB);

        WAXING_MAP_ITEMS.put(Items.CUT_COPPER_STAIRS, Items.WAXED_CUT_COPPER_STAIRS);
        WAXING_MAP_ITEMS.put(Items.EXPOSED_CUT_COPPER_STAIRS, Items.WAXED_EXPOSED_CUT_COPPER_STAIRS);
        WAXING_MAP_ITEMS.put(Items.WEATHERED_CUT_COPPER_STAIRS, Items.WAXED_WEATHERED_CUT_COPPER_STAIRS);
        WAXING_MAP_ITEMS.put(Items.OXIDIZED_CUT_COPPER_STAIRS, Items.WAXED_OXIDIZED_CUT_COPPER_STAIRS);

        WAXING_MAP_ITEMS.put(Items.COPPER_BULB, Items.WAXED_COPPER_BULB);
        WAXING_MAP_ITEMS.put(Items.EXPOSED_COPPER_BULB, Items.WAXED_EXPOSED_COPPER_BULB);
        WAXING_MAP_ITEMS.put(Items.WEATHERED_COPPER_BULB, Items.WAXED_WEATHERED_COPPER_BULB);
        WAXING_MAP_ITEMS.put(Items.OXIDIZED_COPPER_BULB, Items.WAXED_OXIDIZED_COPPER_BULB);

        WAXING_MAP_ITEMS.put(Items.COPPER_DOOR, Items.WAXED_COPPER_DOOR);
        WAXING_MAP_ITEMS.put(Items.EXPOSED_COPPER_DOOR, Items.WAXED_EXPOSED_COPPER_DOOR);
        WAXING_MAP_ITEMS.put(Items.WEATHERED_COPPER_DOOR, Items.WAXED_WEATHERED_COPPER_DOOR);
        WAXING_MAP_ITEMS.put(Items.OXIDIZED_COPPER_DOOR, Items.WAXED_OXIDIZED_COPPER_DOOR);

        WAXING_MAP_ITEMS.put(Items.COPPER_GRATE, Items.WAXED_COPPER_GRATE);
        WAXING_MAP_ITEMS.put(Items.EXPOSED_COPPER_GRATE, Items.WAXED_EXPOSED_COPPER_GRATE);
        WAXING_MAP_ITEMS.put(Items.WEATHERED_COPPER_GRATE, Items.WAXED_WEATHERED_COPPER_GRATE);
        WAXING_MAP_ITEMS.put(Items.OXIDIZED_COPPER_GRATE, Items.WAXED_OXIDIZED_COPPER_GRATE);

        WAXING_MAP_ITEMS.put(Items.COPPER_TRAPDOOR, Items.WAXED_COPPER_TRAPDOOR);
        WAXING_MAP_ITEMS.put(Items.EXPOSED_COPPER_TRAPDOOR, Items.WAXED_EXPOSED_COPPER_TRAPDOOR);
        WAXING_MAP_ITEMS.put(Items.WEATHERED_COPPER_TRAPDOOR, Items.WAXED_WEATHERED_COPPER_TRAPDOOR);
        WAXING_MAP_ITEMS.put(Items.OXIDIZED_COPPER_TRAPDOOR, Items.WAXED_OXIDIZED_COPPER_TRAPDOOR);

        WAXING_MAP_ITEMS.put(Items.CHISELED_COPPER, Items.WAXED_CHISELED_COPPER);
        WAXING_MAP_ITEMS.put(Items.EXPOSED_CHISELED_COPPER, Items.WAXED_EXPOSED_CHISELED_COPPER);
        WAXING_MAP_ITEMS.put(Items.WEATHERED_CHISELED_COPPER, Items.WAXED_WEATHERED_CHISELED_COPPER);
        WAXING_MAP_ITEMS.put(Items.OXIDIZED_CHISELED_COPPER, Items.WAXED_OXIDIZED_CHISELED_COPPER);

        WAXING_MAP_ITEMS.put(Items.COPPER_LANTERN.unaffected(), Items.COPPER_LANTERN.waxed());
        WAXING_MAP_ITEMS.put(Items.COPPER_LANTERN.exposed(), Items.COPPER_LANTERN.waxedExposed());
        WAXING_MAP_ITEMS.put(Items.COPPER_LANTERN.weathered(), Items.COPPER_LANTERN.waxedWeathered());
        WAXING_MAP_ITEMS.put(Items.COPPER_LANTERN.oxidized(), Items.COPPER_LANTERN.waxedOxidized());

        WAXING_MAP_ITEMS.put(Items.COPPER_CHEST, Items.WAXED_COPPER_CHEST);
        WAXING_MAP_ITEMS.put(Items.EXPOSED_COPPER_CHEST, Items.WAXED_EXPOSED_COPPER_CHEST);
        WAXING_MAP_ITEMS.put(Items.WEATHERED_COPPER_CHEST, Items.WAXED_WEATHERED_COPPER_CHEST);
        WAXING_MAP_ITEMS.put(Items.OXIDIZED_COPPER_CHEST, Items.WAXED_OXIDIZED_COPPER_CHEST);

        ARMOR_EFFECTS.put(Items.COPPER_HELMET, new MobEffectInstance(MobEffects.HASTE, 600, 0));
        ARMOR_EFFECTS.put(Items.COPPER_CHESTPLATE, new MobEffectInstance(MobEffects.HASTE, 600, 0));
        ARMOR_EFFECTS.put(Items.COPPER_LEGGINGS, new MobEffectInstance(MobEffects.HASTE, 600, 0));
        ARMOR_EFFECTS.put(Items.COPPER_BOOTS, new MobEffectInstance(MobEffects.HASTE, 600, 0));
    }
}
