modLoader="javafml"
loaderVersion="${neoforge_loader_version_range}"
license="${mod_license}"
issueTrackerURL="https://github.com/Killarexe/Copper-Extension/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/Killarexe/Copper-Extension/master/neoforge/update.json"
displayURL="${mod_url}"
logoFile="assets/copper_extension/logo.png"
authors="Killar"
credits="Thanks to junshengxie for translating!"
displayTest="MATCH_VERSION"
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[dependencies.crystals]]
modId="neoforge"
type="required"
versionRange="${neoforge_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.crystals]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"
